kind: techie
me:
  fullName: Iván Corrales Solera
  email: ivan.corrales.solera@gmail.com
  social:
    twitter: @wesovilabs
    github: ivancorrales
    linkedin: ivan-corrales-solera
ignore:
  - backups/**
  - old
